### ISSUE TITLE
How to clean up after PR merge?

### ISSUE THREAD

**Issue by slaterx** [barecheck/preview-deployment-action#62]
Hi,

Great job on creating this action, it's very straightforward to use it! 

I'm wondering, have you thought how to clean up old previews? Either on-demand with PR merge or automatically via bucket policies?

**Comment by vitaliimelnychuk** [comment]
Hi @slaterx, sorry for a slow reply. I missed the notification about this issue...


It should auto-delete folder once PR is closed but you have to listen for this event in your action, here is where it's implemented:
https://github.com/barecheck/preview-deployment-action/blob/v1/src/main.ts#L88

I am looking to create also support for serverless deployments, let me know if this is something you also would be interested in.

**Comment by slaterx** [comment]
no worries, we ended up setting up a magic cloudfront setting for previewing PRs and jakejarvis/s3-sync-action for synchronizing the content that goes into it.

if you create an end-to-end example of how this would work, we can look into replacing our setup with your action.

**Comment by vitaliimelnychuk** [comment]
Did you use an example from Readme:

```
name: Preview Deployment

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4

      #
      # YOUR APPLICATION BUILD STEPS ARE HERE
      #

      - name: Run deployment preview
        id: s3-preview-deployment-action
        uses: barecheck/preview-deployment-action@v1
        with:
          # The action should run after your static file are built
          build-dir: YOU_STATIC_FILES_OUT_DIR
          # App name will be used to create AWS resources.
          app-name: YOUR_APP_NAME
          # Preview deployments will add `preview-{PR-number}` as subdomain to this domain
          domain: YOUR_DOMAIN_NAME
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_CLOUDFRONT_CERTIFICATE_ARN: ${{ secrets.AWS_CLOUDFRONT_CERTIFICATE_ARN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

This should clean up a folder inside S3 bucket once PR is merged
